# Plugin version: 1.0.0
# This is the main configuration file for the plugin
# This file is used to configure the plugin

#Language: "fr" # The language of the plugin (default: fr) (available: en, fr)
Language: "fr"


# Number of player need to pass the vote
Vote:
  Rain:
    value: 4 # Number of player need to pass the vote
    Percentage: 
      Use: true #if true, it's not a number but a percentage of player need to pass the vote
      value: 25 # Percentage of player need to pass the vote

  Night:
    value: 4 # Number of player need to pass the vote
    Percentage: 
      Use: true #if true, it's not a number but a percentage of player need to pass the vote
      value: 25 # Percentage of player need to pass the vote
    

WelcomeMessage: "Yo man!" # The welcome message that will be displayed when the player joins the server in the actionbar 

Tab:
  Header: "§2La Bienveillance avant tout !§r" # The header of the tablist 
  Footer: "§2La Bienveillance avant tout !§r" # The footer of the tablist

JoinMessage: "§a a rejoint la partie."
LeftMessage: "§c a quitté la partie."

NoGamemode: true # If true, the player will not be able to change his gamemode so put false if you want to allow the player to change his gamemode (default: true)
PVP:
  CheckNoStuff: true